### ISSUE TITLE
Detect changes to PBXNativeTarget during target build up-to-date checking

### ISSUE THREAD

**Issue by lacasseio** [nokeedev/gradle-native#778]
As a user building Xcode targets using Gradle, I want the Gradle tasks representing the Xcode targets to be out-of-date only when its build specification change during an incremental build so I can have accurate feedback.

```[tasklist]
### Sub-stories
- [ ] https://github.com/nokeedev/gradle-native/issues/779
- [ ] https://github.com/nokeedev/gradle-native/issues/780
- [x] https://github.com/nokeedev/gradle-native/issues/781
- [ ] https://github.com/nokeedev/gradle-native/issues/782
- [ ] https://github.com/nokeedev/gradle-native/issues/783
- [ ] https://github.com/nokeedev/gradle-native/issues/784
```

# Acceptance Criteria
- [ ] Any changes to the product type. It usually means deleting and adding a different target with the same name. To narrow it down to the product type, we must find two target types with the same configuration.
- [ ] Any changes to the product name.
- [x] Any changes to build phases that include ordering, adding and removing (separate issues handle the specification of each build phase)
- [ ] Any changes to effective build settings (including project's build settings that are not overwritten)
