### ISSUE TITLE
Detect changes to PBXAggregateTarget during  build up-to-date checking

### ISSUE THREAD

**Issue by lacasseio** [nokeedev/gradle-native#786]
As a user building Xcode targets using Gradle, I want the Gradle tasks representing the Xcode targets to be out-of-date only when its build specification change during an incremental build so I can have accurate feedback.

```[tasklist]
### Sub-stories
- [ ] https://github.com/nokeedev/gradle-native/issues/779
- [ ] https://github.com/nokeedev/gradle-native/issues/780
- [x] https://github.com/nokeedev/gradle-native/issues/781
- [ ] https://github.com/nokeedev/gradle-native/issues/782
- [ ] https://github.com/nokeedev/gradle-native/issues/783
- [ ] https://github.com/nokeedev/gradle-native/issues/784
```

# Acceptance Criteria
- [ ] Any changes to the product type. It usually means deleting and adding a different target with the same name.
- [ ] ~~Any changes to the product name.~~ (Cannot change product name via IDE)
- [x] Any changes to the build phases, e.g. ordering, adding, and removing.
- [ ] Any changes to effective build settings (including project's build settings that are not overwritten)
